#!/bin/bash
make -f binom.mak
make -f captcha.mak
make -f ekisschi.mak
make -f ekissdots.mak
make -f ekissencr.mak
make -f ekissgen.mak
make -f ekissnorm.mak
make -f ekisspat.mak
make -f ekissraw.mak
make -f ekisstim.mak
make -f genalfa.mak
make -f gendna.mak
make -f mcbell.mak
make -f mccos.mak
make -f mchain.mak
make -f mcparab.mak
make -f mcpi.mak
make -f mcsin.mak
make -f mcsph.mak
make -f pair.mak
make -f poischi.mak
make -f pwrball.mak
make -f qmatch.mak
make -f ranwlk.mak
make -f tstekiss.mak
make -f uintchi.mak
